config/routes.rb
Rails.application.routes.draw do

  resources :approval_statuses
  resources :grants
  resources :bounties
  resources :projects
  resources :claimants

  get 'approve_projects',
      to: 'granting_engine#approve_projects',
      as: 'approve_projects'

  get 'adjustment_grants',
      to: 'granting_engine#adjustment_grants',
      as: 'adjustment_grants'

  get 'periodic_grants',
      to: 'granting_engine#periodic_grants',
      as: 'periodic_grants'

end

app/models/claimant.rb
class Claimant < ActiveRecord::Base
	has_many :projects
	has_many :wallets
end

app/controllers/claimants_controller.rb
class ClaimantsController < ApplicationController
  before_action :set_claimant, only: [:show, :edit, :update, :destroy]

  # GET /claimants
  # GET /claimants.json
  def index
    @claimants = Claimant.all
  end

  # GET /claimants/1
  # GET /claimants/1.json
  def show
  end

  # GET /claimants/new
  def new
    @claimant = Claimant.new
  end

  # GET /claimants/1/edit
  def edit
  end

  # POST /claimants
  # POST /claimants.json
  def create
    @claimant = Claimant.new(claimant_params)

    respond_to do |format|
      if @claimant.save
        format.html { redirect_to @claimant, notice: 'Claimant was successfully created.' }
        format.json { render :show, status: :created, location: @claimant }
      else
        format.html { render :new }
        format.json { render json: @claimant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claimants/1
  # PATCH/PUT /claimants/1.json
  def update
    respond_to do |format|
      if @claimant.update(claimant_params)
        format.html { redirect_to @claimant, notice: 'Claimant was successfully updated.' }
        format.json { render :show, status: :ok, location: @claimant }
      else
        format.html { render :edit }
        format.json { render json: @claimant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claimants/1
  # DELETE /claimants/1.json
  def destroy
    @claimant.destroy
    respond_to do |format|
      format.html { redirect_to claimants_url, notice: 'Claimant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claimant
      @claimant = Claimant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claimant_params
      params.require(:claimant).permit(:first_name, :last_name, :email, :country)
    end
end

app/helpers/claimants_helper.rb
module ClaimantsHelper
end

app/views/claimants/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @view_title %></h3>
    </div>
    <div class="panel-body">
      <%= form_for @claimant, layout: :basic do |f| %>
        <% if @claimant.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@claimant.errors.count, 'error') %>
              prohibited this legal entity from being saved
            </h2>

            <ul>
            <% @claimant.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.text_field :email %>
        </div>
        <div class="actions">
          <%= f.submit 'Save' %>
          <%= link_to 'Back', claimants_path, :class => 'btn btn-default'%>
        </div>
      <% end %>
    </div>
</div>

app/views/claimants/edit.html.erb
<% @view_title = 'Edit Legal Entity'%>

<%= render 'form' %>

app/views/claimants/index.html.erb
<% if notice %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p id="notice"><%= notice %></p>
    </div>
    <br/>
<% end %>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Legal Entities</div>
  <div class="panel-body">
    <!--<div class="clearfix">-->
      <!--<span class="pull-right">-->
        <!--<%= link_to 'New Legal Entity', new_claimant_path, :class => "btn btn-primary" %>-->
      <!--</span>-->
    <!--</div>-->
    <!--<hr/>-->
    <div class="table-responsive">
      <table id="claimantsTable" class="table table-hover">
        <thead>
        <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
        </tr>
        </thead>

        <tbody>
        <% @claimants.each do |claimant| %>
            <tr>
              <td><%= link_to "#{claimant.id}", claimant %></td>
              <td><%= claimant.first_name %></td>
              <td><%= claimant.last_name %></td>
              <td><%= claimant.email %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $('#claimantsTable').DataTable({
      "paging": true,
      "ordering": true,
      "info": true,
      "pagingType": "full_numbers"
    });
  });

</script>

app/views/claimants/new.html.erb
<% @view_title = 'New Legal Entity' %>

<%= render 'form' %>

app/views/claimants/show.html.erb
<% if notice %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p id="notice"><%= notice %></p>
    </div>
    <br/>
<% end %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Legal Entity Details</h3>
  </div>
  <div class="panel-body">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>First Name:</strong>
      <%= @claimant.first_name %>
    </p>

    <p>
      <strong>Last Name:</strong>
      <%= @claimant.last_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @claimant.email %>
    </p>

    <%= link_to 'Edit', edit_claimant_path(@claimant) %> |
    <%= link_to 'Back', claimants_path %>

    <hr/>
    <h5>Projects</h5>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Nameplate</th>
        <th>Country</th>
        <th>Install Date</th>
        <th>Status</th>
        <th>Docs</th>
        <th>Wallet</th>
      </tr>
      </thead>

      <tbody>
      <% @claimant.projects.each do |project| %>
          <tr>
            <td><%= project.nameplate %></td>
            <td><%= project.country %></td>
            <td><%= project.install_date %></td>
            <td><%= project.status %></td>
            <td><%= project.documentation %></td>
            <td><%= project.wallet_address %></td>
            <td><%= link_to 'Show', project %></td>
          </tr>
      <% end %>
      </tbody>
    </table>


  </div>
</div>