config/routes.rb
Rails.application.routes.draw do

  resources :approval_statuses
  resources :grants
  resources :bounties
  resources :projects
  resources :claimants

  get 'approve_projects',
      to: 'granting_engine#approve_projects',
      as: 'approve_projects'

  get 'adjustment_grants',
      to: 'granting_engine#adjustment_grants',
      as: 'adjustment_grants'

  get 'periodic_grants',
      to: 'granting_engine#periodic_grants',
      as: 'periodic_grants'

end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
	belongs_to :project
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]
  after_action :set_guid, only: [:create, :update]

  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all
  end

  # GET /bounties/1
  # GET /bounties/1.json
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new
  end

  # GET /bounties/1/edit
  def edit
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(bounty_params)

    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: 'Bounty was successfully created.' }
        format.json { render :show, status: :created, location: @bounty }
      else
        format.html { render :new }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bounties/1
  # PATCH/PUT /bounties/1.json
  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: 'Bounty was successfully updated.' }
        format.json { render :show, status: :ok, location: @bounty }
      else
        format.html { render :edit }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  def destroy
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to bounties_url, notice: 'Bounty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    def set_guid
      grant = @bounty.grant
      @bounty.GUID = "BGRT-#{grant.project.country}-#{grant.project.post_code}-#{grant.project.id}-#{grant.project.nameplate}-#{grant.project.install_date.to_formatted_s(:iso8601)}"
      @bounty.save
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bounty_params
      params.require(:bounty).permit(:GUID, :amount, :receiver_wallet, :grant_id)
    end
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/views/bounties/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @view_title %></h3>
    </div>
    <div class="panel-body">
      <%= form_for @bounty, layout: :basic do |f| %>
        <div class="field">
          <%= f.text_field :amount %>
        </div>
        <div class="field">
          <%= f.text_field :receiver_wallet %>
        </div>
        <div class="field">
          <%= f.text_field :grant_id %>
        </div>
        <div class="actions">
          <%= f.submit %>
          <%= link_to "Back", bounties_path, :class => "btn btn-default" %>
        </div>
      <% end %>
    </div>
</div>

app/views/bounties/edit.html.erb
<% @view_title = "Edit Bounty" %>

<%= render 'form' %>

app/views/bounties/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Bounty Grants</div>
    <div class="panel-body">
      <span class="pull-right">
        <%= link_to 'New Bounty', new_bounty_path, :class => "btn btn-primary" %>
      </span>
    </div>

    <table id="bountiesTable" class="table table-hover">
      <thead>
        <tr>
          <th>GUID</th>
          <th>Amount</th>
          <th>Receiver wallet</th>
          <th>Grant GUID</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @bounties.each do |bounty| %>
          <tr>
            <td><%= bounty.GUID %></td>
            <td><%= solar_coin_amount(bounty.amount) %></td>
            <td><%= bounty.wallet.public_address %></td>
            <td><%= bounty.grant.GUID %></td>
            <td><%= link_to 'Show', bounty %></td>
            <td><%= link_to 'Edit', edit_bounty_path(bounty) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#bountiesTable').DataTable( {
      "paging": true,
      "ordering": true,
      "info": true,
      "pagingType": "full_numbers"
    });
  });

</script>

app/views/bounties/new.html.erb
<% @view_title = "New Bounty" %>

<%= render 'form' %>

app/views/bounties/show.html.erb
<% if notice %>
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p id="notice"><%= notice %></p>
</div>
<br/>
<% end %>

<div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Bounty Details</h3>
    </div>
    <div class="panel-body">
      <p>
        <strong>Guid:</strong>
        <%= @bounty.GUID %>
      </p>

      <p>
        <strong>Amount:</strong>
        <%= solar_coin_amount(@bounty.amount) %>
      </p>

      <p>
        <strong>Receiver wallet:</strong>
        <%= @bounty.wallet.public_address %>
      </p>

      <p>
        <strong>Grant:</strong>
        <%= @bounty.grant.GUID %>
      </p>

      <%= link_to 'Edit', edit_bounty_path(@bounty) %> |
      <%= link_to 'Back', bounties_path %>

    </div>
</div>