config/routes.rb
Rails.application.routes.draw do

  resources :approval_statuses
  resources :grants
  resources :bounties
  resources :projects
  resources :claimants

  get 'approve_projects',
      to: 'granting_engine#approve_projects',
      as: 'approve_projects'

  get 'adjustment_grants',
      to: 'granting_engine#adjustment_grants',
      as: 'adjustment_grants'

  get 'periodic_grants',
      to: 'granting_engine#periodic_grants',
      as: 'periodic_grants'

end

app/controllers/approval_statuses_controller.rb
class ApprovalStatusesController < ApplicationController
  before_action :set_approval_status, only: [:show, :edit, :update, :destroy]

  # GET /approval_statuses
  # GET /approval_statuses.json
  def index
    @approval_statuses = ApprovalStatus.all
  end

  # GET /approval_statuses/1
  # GET /approval_statuses/1.json
  def show
  end

  # GET /approval_statuses/new
  def new
    @approval_status = ApprovalStatus.new
  end

  # GET /approval_statuses/1/edit
  def edit
  end

  # POST /approval_statuses
  # POST /approval_statuses.json
  def create
    @approval_status = ApprovalStatus.new(approval_status_params)

    respond_to do |format|
      if @approval_status.save
        format.html { redirect_to @approval_status, notice: 'Approval status was successfully created.' }
        format.json { render :show, status: :created, location: @approval_status }
      else
        format.html { render :new }
        format.json { render json: @approval_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approval_statuses/1
  # PATCH/PUT /approval_statuses/1.json
  def update
    respond_to do |format|
      if @approval_status.update(approval_status_params)
        format.html { redirect_to @approval_status, notice: 'Approval status was successfully updated.' }
        format.json { render :show, status: :ok, location: @approval_status }
      else
        format.html { render :edit }
        format.json { render json: @approval_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approval_statuses/1
  # DELETE /approval_statuses/1.json
  def destroy
    @approval_status.destroy
    respond_to do |format|
      format.html { redirect_to approval_statuses_url, notice: 'Approval status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approval_status
      @approval_status = ApprovalStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def approval_status_params
      params.require(:approval_status).permit(:code, :details)
    end
end

app/helpers/approval_statuses_helper.rb
module ApprovalStatusesHelper
end

app/views/approval_statuses/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @view_title %></h3>
    </div>
    <div class="panel-body">
      <%= form_for @approval_status, layout: :basic do |f| %>
        <%= f.text_field :code %>
        <%= f.text_field :details %>
        <%= f.submit %>
        <%= link_to 'Back', approval_statuses_path,:class => "btn btn-default" %>
      <% end %>
    </div>
</div>

app/views/approval_statuses/edit.html.erb
<% @view_title = "Editing Approval Status" %>

<%= render 'form' %>

app/views/approval_statuses/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Approval Status Codes</h3>
    </div>
    <div class="panel-body">
      <span class="pull-right">
        <%= link_to 'New Approval status', new_approval_status_path, :class => "btn btn-primary" %>
      </span>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Code</th>
            <th>Details</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @approval_statuses.each do |approval_status| %>
            <tr>
              <td><%= approval_status.code %></td>
              <td><%= approval_status.details %></td>
              <td><%= link_to 'Show', approval_status %></td>
              <td><%= link_to 'Edit', edit_approval_status_path(approval_status) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
</div>

app/views/approval_statuses/new.html.erb
<% @view_title = "New Approval Status" %>

<%= render 'form' %>

app/views/approval_statuses/show.html.erb
<% if notice %>
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p id="notice"><%= notice %></p>
</div>
<br/>
<% end %>

<div class="panel panel-info">
	  <div class="panel-heading">
			<h3 class="panel-title">Approval Status Details</h3>
	  </div>
	  <div class="panel-body">
	  	<p>
	  	  <strong>Code:</strong>
	  	  <%= @approval_status.code %>
	  	</p>

	  	<p>
	  	  <strong>Details:</strong>
	  	  <%= @approval_status.details %>
	  	</p>

	  	<%= link_to 'Edit', edit_approval_status_path(@approval_status) %> |
	  	<%= link_to 'Back', approval_statuses_path %>			
	  </div>
</div>