config/routes.rb
Rails.application.routes.draw do

  resources :approval_statuses
  resources :grants
  resources :bounties
  resources :projects
  resources :claimants

  get 'approve_projects',
      to: 'granting_engine#approve_projects',
      as: 'approve_projects'

  get 'adjustment_grants',
      to: 'granting_engine#adjustment_grants',
      as: 'adjustment_grants'

  get 'periodic_grants',
      to: 'granting_engine#periodic_grants',
      as: 'periodic_grants'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Solaris</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS & JS -->

  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/paper/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.c  om/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="//twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.min.js"></script>
  <style type="text/css">
  	.twitter-typeahead { width: 100%; }
  	.typeahead:focus {
  	  border: 2px solid #0097cf;
  	}

  	.tt-query {
  	  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  	     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  	          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  	}

  	.tt-hint {
  	  color: #999;
  	  width: 100%;
  	}

  	.tt-menu {
  	  width: 100%;
  	  /*margin: 12px 0;*/
  	  padding: 8px 0;
  	  background-color: #fff;
  	  border: 1px solid #ccc;
  	  border: 1px solid rgba(0, 0, 0, 0.2);
  	  -webkit-border-radius: 8px;
  	     -moz-border-radius: 8px;
  	          border-radius: 8px;
  	  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
  	     -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
  	          box-shadow: 0 5px 10px rgba(0,0,0,.2);
  	}

  	.tt-suggestion {
  	  padding: 3px 20px;
  	  /*font-size: 18px;*/
  	  line-height: 24px;
  	}

  	.tt-suggestion:hover {
  	  cursor: pointer;
  	  color: #fff;
  	  background-color: #0097cf;
  	}

  	.tt-suggestion.tt-cursor {
  	  color: #fff;
  	  background-color: #0097cf;

  	}

  	.tt-suggestion p {
  	  margin: 0;
  	}
  </style>
</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button"
              class="navbar-toggle"
              data-toggle="collapse"
              data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Solaris</a>
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Approval <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Facilities', projects_path%></li>
            <li><%= link_to 'Approval Status Codes', approval_statuses_path %></li>
          </ul>
        </li>
	      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Granting <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Execute Facility Approvals', approve_projects_path %>
            </li>
            <li>
              <%= link_to 'Execute Adjustment Grants', adjustment_grants_path %>
            </li>
            <li>
              <%= link_to 'Execute Periodic Grants', periodic_grants_path %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Reports <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Facilities', projects_path %></li>
            <li><%= link_to 'Grants', grants_path %></li>
          </ul>
        </li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</nav>
	<div class="container" style="width:<%= params[:action] == 'index' ? '95%' : '' %>">
		<%= yield %>
	</div>
</body>
</html>